//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bill()
        {
            this.products = new HashSet<product>();
        }

        [Display(Name = "BillID")]
        public int billID { get; set; }
        [Display(Name = "UserName")]
        public string username { get; set; }
        [Display(Name = "Weight(gram)")]
        public decimal weight { get; set; }
        [Display(Name = "length(cm)")]
        public decimal lenght { get; set; }
        [Display(Name = "Width(cm)")]
        public decimal width { get; set; }
        [Display(Name = "Description")]
        public string description { get; set; }
        [Display(Name = "Name")]
        public string name { get; set; }
        [Display(Name = "Receiver Name")]
        public string receivername { get; set; }
        [Display(Name = "Sent Name")]
        public string sentname { get; set; }
        [Display(Name = "Sent Address")]
        public string sentaddress { get; set; }
        [Display(Name = "Receiver Address")]
        public string receiveraddress { get; set; }
        [Display(Name = "Total")]
        [DataType(DataType.Currency)]
        public decimal total { get; set; }
        [Display(Name = "LocationID")]
        public int locationID { get; set; }
        [Display(Name = "Quantity")]
        public int quantity { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.Date)]
        [Display(Name = "Date")]
        public System.DateTime date { get; set; }
        [Display(Name = "Status")]
        public bool status { get; set; }
        [Display(Name ="Height")]
        public decimal height { get; set; }
    
        public virtual location location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> products { get; set; }
    }
}
