//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Member
    {
        [Display(Name = "MemID")]
        public int memID { get; set; }
        [Display(Name = "UserName")]
        public string username { get; set; }
        [Display(Name = "FullName")]
        public string fullname { get; set; }
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string pass { get; set; }
        [Display(Name = "Phone Number")]
        [DataType(DataType.PhoneNumber)]
        public string phone { get; set; }
        [Display(Name = "Address")]
        public string address { get; set; }
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }
    }
}
