//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        [Display(Name = "Weight(gram)")]
        public decimal weight { get; set; }
        [Display(Name = "Length(cm)")]
        public decimal lenght { get; set; }
        [Display(Name = "Height(cm)")]
        public decimal height { get; set; }
        [Display(Name = "Width(cm)")]
        public decimal width { get; set; }
        [Display(Name = "Description")]
        public string description { get; set; }
        [Display(Name = "Name")]
        public string name { get; set; }
        [Display(Name = "ProID")]
        public int proID { get; set; }
        [Display(Name = "BillID")]
        public int billID { get; set; }

        public virtual bill bill { get; set; }
    }
}
